libstagefright: fix format conflict in log output
Convert format of variable in log output to avoid this error:

frameworks/av/media/libstagefright/codecs/mp3dec/SoftMP3.cpp:279:17: error: format
specifies type 'unsigned long' but the argument has type 'OMX_U32' (aka 'unsigned
int') [-Werror,-Wformat]

Change-Id: Ied75a05fdf8b330704258a2f866cd942e608e2e9
Signed-off-by: Svyatoslav Ryhel <clamor95@gmail.com>